
    create table if not exists aluno (
        endereco_id bigint unique,
        id bigint generated by default as identity,
        ano varchar(255),
        cpf varchar(255),
        email varchar(255),
        matricula varchar(255),
        nome varchar(255),
        senha varchar(255),
        telefone varchar(255),
        primary key (id)
    );

    create table if not exists aluno_turma (
        media numeric(38,2),
        aluno_id bigint unique,
        id bigint generated by default as identity,
        turma_id bigint unique,
        primary key (id)
    );

    create table if not exists avaliacao (
        nota numeric(2,2) not null,
        tipo smallint check (tipo between 0 and 3),
        aluno_id bigint,
        id bigint generated by default as identity,
        turma_id bigint,
        primary key (id)
    );

    create table if not exists conversa (
        aluno_id bigint,
        data_criacao timestamp(6),
        id bigint generated by default as identity,
        professor_id bigint,
        primary key (id)
    );

    create table if not exists disciplina (
        id bigint generated by default as identity,
        bibliografia varchar(255),
        carga_horaria varchar(255),
        codigo varchar(255),
        descricao varchar(255),
        ementa varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table if not exists endereco (
        id bigint generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        cidade varchar(255),
        complemento varchar(255),
        estado varchar(255),
        logradouro varchar(255),
        numero varchar(255),
        primary key (id)
    );

    create table if not exists evento (
        data timestamp(6),
        id bigint generated by default as identity,
        descricao varchar(255),
        local varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table if not exists frequencia (
        data date,
        presente boolean,
        aluno_turma_id bigint,
        id bigint generated by default as identity,
        primary key (id)
    );

    create table if not exists mensagem (
        conversa_id bigint,
        data_envio timestamp(6),
        id bigint generated by default as identity,
        remetente_id bigint,
        conteudo varchar(255),
        primary key (id)
    );

    create table if not exists merenda (
        turno smallint check (turno between 0 and 2),
        id bigint generated by default as identity,
        descricao varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table if not exists parente (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255),
        nome varchar(255),
        senha varchar(255),
        telefone varchar(255),
        primary key (id)
    );

    create table if not exists parente_aluno (
        aluno_id bigint not null,
        parente_id bigint not null,
        primary key (aluno_id, parente_id)
    );

    create table if not exists professor (
        endereco_id bigint unique,
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255),
        especialidade varchar(255),
        lattes varchar(255),
        matricula varchar(255),
        nome varchar(255),
        senha varchar(255),
        telefone varchar(255),
        primary key (id)
    );

    create table if not exists turma (
        horario time(6),
        disciplina_id bigint,
        id bigint generated by default as identity,
        professor_id bigint,
        ano varchar(255),
        codigo varchar(255),
        nome varchar(255),
        sala varchar(255),
        primary key (id)
    );

    alter table if exists aluno
       add constraint FKeooy7cntssxbfvyx7odcig95j
       foreign key (endereco_id)
       references endereco;

    alter table if exists aluno_turma
       add constraint FK2fj61l46624xf38hvfb9kqgrw
       foreign key (aluno_id)
       references aluno;

    alter table if exists aluno_turma
       add constraint FKmy58tj0pmjjv5tcv89ik43344
       foreign key (turma_id)
       references turma;

    alter table if exists avaliacao
       add constraint FK59p9elukmwcs4h8p1qo05c7bw
       foreign key (aluno_id)
       references aluno;

    alter table if exists avaliacao
       add constraint FKocfuxny1ed0d65ytva0oqtnpt
       foreign key (turma_id)
       references turma;

    alter table if exists conversa
       add constraint FKljtuurxv1i25d56ctuhomkwi8
       foreign key (aluno_id)
       references aluno;

    alter table if exists conversa
       add constraint FK3bm5yrggubax8dtquwacd3ytm
       foreign key (professor_id)
       references professor;

    alter table if exists frequencia
       add constraint FK3wmqxv7x27sy9c2s0xxmbn0u6
       foreign key (aluno_turma_id)
       references aluno_turma;

    alter table if exists mensagem
       add constraint FKc4wr60fmbp841ipcdr9h0m17v
       foreign key (conversa_id)
       references conversa;

    alter table if exists parente_aluno
       add constraint FKcy3ostu9jlx8c187jeie9l0l3
       foreign key (aluno_id)
       references aluno;

    alter table if exists parente_aluno
       add constraint FKmacmr8s9ihrd3crk1pdwe93uf
       foreign key (parente_id)
       references parente;

    alter table if exists professor
       add constraint FKf3kci47kb5v2ma4dsqmk6cmnb
       foreign key (endereco_id)
       references endereco;

    alter table if exists turma
       add constraint FKeee13bbo1a87bo2i3bxxwvegm
       foreign key (disciplina_id)
       references disciplina;

    alter table if exists turma
       add constraint FK9xwtpw9i63l1u1uevrsdc6g69
       foreign key (professor_id)
       references professor;